version: '3.8'
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "9080:9080"

  user-service:
    build: ./services/user-service
    ports:
      - "8080:8080"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
